# Generated by Django 3.2 on 2021-06-06 11:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25, verbose_name='نام')),
                ('last_name', models.CharField(max_length=25, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='phone number invalid', regex='^0[0-9]{2,}[0-9]{7,}$')], verbose_name='شماره تلفن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('auto_increment_id', 'user')},
            },
        ),
    ]
