# Generated by Django 3.2 on 2021-06-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonebook',
            unique_together=set(),
        ),
    ]
