# Generated by Django 3.2 on 2021-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_phonebook_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
